### ISSUE TITLE
Approfondimenti consigliati

### ISSUE THREAD

**Issue by Flecart** [cartabinaria/fondamenti-di-cybersecurity#15]
La prof. ogni tanto dà links di risorse di approfondimento, tipo https://crypto.stanford.edu/~dabo/courses/OnlineCrypto/.
Sarebbe sensato metterli da qualche parte?

**Comment by ali-benny** [comment]
Potresti aggiungerle a `varie/` secondo me

**Comment by samuelemusiani** [comment]
@Flecart bump

**Comment by Flecart** [comment]
Thanks, lo metto
