### ISSUE TITLE
Broken PDF when downloading with icon

### ISSUE THREAD

**Issue by Flecart** [cartabinaria/fondamenti-di-cybersecurity#17]
Sul sito principale il pdf non funziona, accedendo da github invece sì 

Link funzionante: https://github.com/csunibo/fondamenti-di-cybersecurity/blob/main/lucidi/jocelyn/00-key-exchange.pdf

Link non funzionante: 
https://risorse.students.cs.unibo.it/fondamenti-di-cybersecurity/lucidi/jocelyn?from=informatica

Scaricare con 
![image](https://github.com/csunibo/fondamenti-di-cybersecurity/assets/63465494/dfc449c4-99eb-47da-a9e8-9240f3198bf1)

**Comment by foxyseta** [comment]
Duplicato di https://github.com/csunibo/dynamik/issues/189.
